#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l vmem=32gb
#PBS -l walltime=05:00:00

MAXMEM=16000000 singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/remove_tracts_from_prediction
if [ ! -f dwi.nii.gz ]; then
    echo "failed to produce dwi output"
    exit 1
fi
